# Generated by Django 5.0.3 on 2024-10-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('family_problem', models.JSONField(default=list)),
                ('family_details', models.TextField()),
                ('friends_problem', models.JSONField(default=list)),
                ('friends_details', models.TextField()),
                ('health_problem', models.JSONField(default=list)),
                ('health_details', models.TextField()),
                ('academic_problem', models.JSONField(default=list)),
                ('academic_details', models.TextField()),
                ('career_problem', models.JSONField(default=list)),
                ('career_details', models.TextField()),
                ('remarks', models.TextField()),
                ('reommendation', models.JSONField(default=list)),
            ],
        ),
    ]
