# Generated by Django 5.0.3 on 2024-10-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_routineinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineinterview',
            name='other_recommendation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
