# Generated by Django 5.0.3 on 2024-10-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_routineinterview_other_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineinterview',
            name='academic_details',
        ),
        migrations.RemoveField(
            model_name='routineinterview',
            name='academic_problem',
        ),
        migrations.RemoveField(
            model_name='routineinterview',
            name='career_details',
        ),
        migrations.RemoveField(
            model_name='routineinterview',
            name='career_problem',
        ),
        migrations.RemoveField(
            model_name='routineinterview',
            name='family_details',
        ),
        migrations.RemoveField(
            model_name='routineinterview',
            name='family_problem',
        ),
        migrations.RemoveField(
            model_name='routineinterview',
            name='friends_details',
        ),
        migrations.RemoveField(
            model_name='routineinterview',
            name='friends_problem',
        ),
        migrations.RemoveField(
            model_name='routineinterview',
            name='health_details',
        ),
        migrations.RemoveField(
            model_name='routineinterview',
            name='health_problem',
        ),
        migrations.RemoveField(
            model_name='routineinterview',
            name='other_recommendation',
        ),
        migrations.RemoveField(
            model_name='routineinterview',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='routineinterview',
            name='reommendation',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Counselor', 'counselor'), ('Psychometrician', 'psychometrician'), ('Student', 'student')], max_length=50),
        ),
    ]
