# Generated by Django 5.0.3 on 2024-10-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_routineinterview_academic_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineinterview',
            name='family_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineinterview',
            name='family_problem',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='routineinterview',
            name='friends_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineinterview',
            name='friends_problem',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='routineinterview',
            name='health_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineinterview',
            name='health_problem',
            field=models.JSONField(default=list),
        ),
    ]
