# Generated by Django 5.0.3 on 2024-10-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_routineinterview_family_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineinterview',
            name='family_problem',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='routineinterview',
            name='friends_problem',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='routineinterview',
            name='health_problem',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
