# Generated by Django 5.0.3 on 2024-10-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_routineinterview_family_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineinterview',
            name='academic_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineinterview',
            name='academic_problem',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='routineinterview',
            name='career_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineinterview',
            name='career_problem',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='routineinterview',
            name='other_recommendation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='routineinterview',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineinterview',
            name='reommendation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
