# Generated by Django 5.0.3 on 2024-10-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_routineinterview_academic_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routineinterview',
            old_name='reommendation',
            new_name='recommendation',
        ),
    ]
