# Generated by Django 5.0.3 on 2024-10-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_individualrecordform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualrecordform',
            name='club',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='completeAddress',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='fatherContactNumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='fatherEmailAddress',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='fatherName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='fatherOccupation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='middlename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='motherContactNumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='motherEmailAddress',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='motherName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='motherOccupation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='relationship',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='section',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
