# Generated by Django 5.0.3 on 2024-10-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_individualrecordform_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualrecordform',
            name='relationship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
