# Generated by Django 5.0.3 on 2024-10-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_individualrecordform_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualrecordform',
            name='completeAddress',
            field=models.CharField(max_length=500),
        ),
    ]
