# Generated by Django 5.0.3 on 2024-10-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_individualrecordform_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_Two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=100)),
                ('sex', models.JSONField(default=list)),
                ('gradeLevel', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('verbalInterpretation', models.CharField(max_length=500)),
                ('stanine', models.CharField(max_length=255)),
                ('sa', models.CharField(max_length=255)),
                ('mme', models.CharField(max_length=255)),
                ('sm', models.CharField(max_length=255)),
                ('e', models.CharField(max_length=255)),
                ('hr', models.CharField(max_length=255)),
            ],
        ),
    ]
