# Generated by Django 5.0.3 on 2024-10-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_grade_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade_two',
            name='totalEQ',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
