# Generated by Django 5.0.3 on 2024-10-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_grade_three'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_Four',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('sex', models.JSONField(default=list)),
                ('gradeLevel', models.CharField(max_length=255)),
                ('section', models.JSONField(default=list)),
                ('conduct', models.JSONField(default=list)),
                ('self_image', models.JSONField(default=list)),
                ('worry', models.JSONField(default=list)),
                ('neg_perl_rel', models.JSONField(default=list)),
                ('antisocial', models.JSONField(default=list)),
                ('lie', models.JSONField(default=list)),
                ('problem_index', models.JSONField(default=list)),
                ('c', models.CharField(max_length=255)),
                ('si', models.CharField(max_length=255)),
                ('w', models.CharField(max_length=255)),
                ('npr', models.CharField(max_length=255)),
                ('a_s', models.CharField(max_length=255)),
                ('l', models.CharField(max_length=255)),
                ('pi', models.CharField(max_length=255)),
            ],
        ),
    ]
