# Generated by Django 5.0.3 on 2024-10-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_grade_six'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_Seven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('sex', models.JSONField(default=list)),
                ('gradeLevel', models.CharField(max_length=255)),
                ('section', models.JSONField(default=list)),
                ('tot', models.JSONField(default=list)),
                ('beh', models.JSONField(default=list)),
                ('inte', models.JSONField(default=list)),
                ('phy', models.JSONField(default=list)),
                ('fre', models.JSONField(default=list)),
                ('popularity', models.JSONField(default=list)),
                ('hap', models.JSONField(default=list)),
                ('py', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='routineinterview',
            name='grade',
            field=models.CharField(choices=[('Grade 1', 'grade 1'), ('Grade 2', 'grade 2'), ('Grade 3', 'grade 3'), ('Grade 4', 'grade 4'), ('Grade 5', 'grade 5'), ('Grade 6', 'grade 6'), ('Grade 7', 'grade 7'), ('Grade 8', 'grade 8'), ('Grade 9', 'grade 9'), ('Grade 10', 'grade 10'), ('Grade 11', 'grade 11'), ('Grade 12', 'grade 12'), ('1st Year', '1st year'), ('2nd Year', '2nd year'), ('3rd Year', '3rd year'), ('4th Year', '4th year')], max_length=100),
        ),
    ]
