# Generated by Django 5.0.3 on 2024-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_grade_seven_alter_routineinterview_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade_seven',
            name='py',
        ),
        migrations.AddField(
            model_name='grade_seven',
            name='beh_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade_seven',
            name='fre_num',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='grade_seven',
            name='hap_num',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='grade_seven',
            name='int_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade_seven',
            name='phy_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade_seven',
            name='popularity_num',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
