# Generated by Django 5.0.3 on 2024-10-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_grade_eight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_Nine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.JSONField(default=list)),
                ('gradeLevel', models.CharField(max_length=255)),
                ('section', models.JSONField(default=list)),
                ('top_one', models.JSONField(default=list)),
                ('top_two', models.JSONField(default=list)),
                ('top_three', models.JSONField(default=list)),
                ('self_control', models.JSONField(default=list)),
                ('mas_fem', models.JSONField(default=list)),
                ('status', models.JSONField(default=list)),
                ('infrequency', models.JSONField(default=list)),
                ('acquiescence', models.JSONField(default=list)),
                ('r', models.CharField(max_length=250)),
                ('i', models.CharField(max_length=250)),
                ('a', models.CharField(max_length=250)),
                ('s', models.CharField(max_length=250)),
                ('e', models.CharField(max_length=250)),
                ('c', models.CharField(max_length=250)),
                ('se', models.CharField(max_length=250)),
                ('mf', models.CharField(max_length=250)),
                ('st', models.CharField(max_length=250)),
                ('inf', models.CharField(max_length=250)),
                ('ac', models.CharField(max_length=250)),
            ],
        ),
    ]
