# Generated by Django 5.0.3 on 2024-10-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_grade_ten'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerTracking_GradeSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.IntegerField()),
                ('english', models.IntegerField()),
                ('filipino', models.IntegerField()),
                ('ap', models.IntegerField()),
                ('science', models.IntegerField()),
                ('math', models.IntegerField()),
                ('mapeh', models.IntegerField()),
                ('tle', models.IntegerField()),
                ('computer', models.IntegerField()),
                ('fl', models.IntegerField()),
                ('academic_track', models.JSONField(default=list)),
                ('other_track', models.CharField(max_length=255)),
                ('tech_voc', models.JSONField(default=list)),
                ('other_techvoc', models.CharField(max_length=255)),
                ('preferredCourse', models.CharField(max_length=255)),
                ('medical_records', models.JSONField(default=list)),
                ('specify', models.CharField(max_length=255)),
                ('academic_status', models.JSONField(default=list)),
                ('psych_results', models.CharField(max_length=255)),
            ],
        ),
    ]
