# Generated by Django 5.0.3 on 2024-10-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_careertracking_gradesix'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CareerTracking_GradeSix',
            new_name='CareerTracking',
        ),
    ]
