# Generated by Django 5.0.3 on 2024-10-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_careertracking_gradesix_careertracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careertracking',
            name='other_techvoc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careertracking',
            name='other_track',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careertracking',
            name='specify',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
