# Generated by Django 5.0.3 on 2024-10-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_careertracking_other_techvoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careertracking',
            name='academic_track',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='careertracking',
            name='preferredCourse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careertracking',
            name='tech_voc',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
