# Generated by Django 5.0.3 on 2024-10-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_careertracking_academic_track_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherConferenceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('grade', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('teachers', models.CharField(max_length=500)),
                ('purpose', models.JSONField(default=list)),
                ('others', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('recommendations', models.TextField()),
            ],
        ),
    ]
