# Generated by Django 5.0.3 on 2024-10-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_teacherconferenceform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherconferenceform',
            name='others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
