# Generated by Django 5.0.3 on 2024-10-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_teacherconferenceform_others'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.JSONField(default=list)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('grade', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('teachers', models.CharField(max_length=500)),
                ('purpose', models.JSONField(default=list)),
                ('others', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField()),
                ('recommendations', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherConferenceForm',
        ),
    ]
