# Generated by Django 5.0.3 on 2024-10-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceform',
            name='type',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
