# Generated by Django 5.0.3 on 2024-10-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='author',
        ),
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.ManyToManyField(related_name='resources', to='api.user'),
        ),
    ]
