# Generated by Django 5.0.3 on 2024-10-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_resource_author_resource_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='resource/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='resource', to='api.user'),
        ),
    ]
