# Generated by Django 5.0.3 on 2024-10-27 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_resource_attachment_alter_resource_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='resource', to=settings.AUTH_USER_MODEL),
        ),
    ]
