# Generated by Django 5.0.3 on 2024-11-09 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_careertracking_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='counselor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_appointments', to='api.profile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sr_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.individualrecordform'),
        ),
        migrations.AddField(
            model_name='individualrecordform',
            name='profile',
            field=models.ForeignKey(db_column='custom_user_column', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='individual_records', to='api.profile'),
        ),
        migrations.AddField(
            model_name='individualrecordform',
            name='sr_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
