# Generated by Django 5.0.3 on 2024-11-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_appointment_counselor_appointment_sr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualrecordform',
            name='profile',
            field=models.ForeignKey(blank=True, db_column='custom_user_column', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_records', to='api.profile'),
        ),
    ]
