# Generated by Django 5.0.3 on 2024-11-12 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_individualrecordform_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualrecordform',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
