# Generated by Django 5.0.3 on 2024-11-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_individualrecordform_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('counselor', 'counselor'), ('psychometrician', 'psychometrician'), ('student', 'student')], max_length=50),
        ),
    ]
