# Generated by Django 5.0.3 on 2024-11-17 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20241118_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualrecordform',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
