# Generated by Django 5.0.3 on 2024-11-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_individualrecordform_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualrecordform',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='individual_record_forms', to='api.profile'),
        ),
    ]
