# Generated by Django 5.0.3 on 2024-11-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_individualrecordform_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualrecordform',
            name='id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_appointments', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.individualrecordform'),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='sr_code',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
