# Generated by Django 5.0.3 on 2024-11-18 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_remove_individualrecordform_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='counselor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_appointments', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sr_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='api.individualrecordform'),
        ),
    ]
