# Generated by Django 5.0.3 on 2024-11-18 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_appointment_counselor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
